### ISSUE TITLE
make all error

### ISSUE THREAD

**Issue by GregorWedlich** [adshao/ordinals-indexer#4]
If i run `make all` i get the following error:

```
╰─ make all                                                                                                                                                     ─╯
make api
make[1]: Entering directory '/home/user/Projects/ordinals/OrdinalsIndexer'
protoc --proto_path=./api \
       --proto_path=./third_party \
 	       --go_out=paths=source_relative:./api \
 	       --go-http_out=paths=source_relative:./api \
 	       --go-grpc_out=paths=source_relative:./api \
       --openapi_out=fq_schema_naming=true,default_response=false,naming=proto:. \
	   --experimental_allow_proto3_optional \
       api/token/v1/token.proto api/token/v1/error_reason.proto api/collection/v1/collection.proto api/collection/v1/error_reason.proto api/inscription/v1/inscription.proto api/inscription/v1/error_reason.proto
make[1]: Leaving directory '/home/user/Projects/ordinals/OrdinalsIndexer'
make errors
make[1]: Entering directory '/home/user/Projects/ordinals/OrdinalsIndexer'
protoc --proto_path=. \
         --proto_path=./third_party \
         --go_out=paths=source_relative:. \
         --go-errors_out=paths=source_relative:. \
	 --experimental_allow_proto3_optional \
         api/token/v1/token.proto api/token/v1/error_reason.proto api/collection/v1/collection.proto api/collection/v1/error_reason.proto api/inscription/v1/inscription.proto api/inscription/v1/error_reason.proto
make[1]: Leaving directory '/home/user/Projects/ordinals/OrdinalsIndexer'
make config
make[1]: Entering directory '/home/user/Projects/ordinals/OrdinalsIndexer'
protoc --proto_path=./internal \
       --proto_path=./third_party \
 	       --go_out=paths=source_relative:./internal \
       internal/conf/conf.proto
make[1]: Leaving directory '/home/user/Projects/ordinals/OrdinalsIndexer'
make db
make[1]: Entering directory '/home/user/Projects/ordinals/OrdinalsIndexer'
go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/upsert --target ./internal/data/ent ./internal/data/ent/schema
panic: template: decode.tmpl:19: unexpected " " in in {{continue}}

goroutine 1 [running]:
entgo.io/ent/entc/gen.MustParse(...)
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/template.go:339
entgo.io/ent/entc/gen.initTemplates()
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/template.go:225 +0x73b
entgo.io/ent/entc/gen.(*Graph).templates(0xc0006ec580)
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/graph.go:879 +0x36
entgo.io/ent/entc/gen.generate(0xc0006ec580)
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/graph.go:225 +0x3f
entgo.io/ent/entc/gen.GenerateFunc.Generate(0x3?, 0x4?)
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/graph.go:143 +0x1f
entgo.io/ent/entc/gen.(*Graph).Gen(0xc0006ec580)
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/graph.go:216 +0x96
entgo.io/ent/entc.generate({0x7fff090790d3, 0x1a}, 0x50?)
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/entc/entc.go:389 +0x92
entgo.io/ent/entc.Generate({0x7fff090790d3, 0x1a}, 0xc000158900, {0xc000375cd0, 0x2, 0x0?})
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/entc/entc.go:86 +0x21f
entgo.io/ent/cmd/internal/base.GenerateCmd.func1(0xc0001f5500?, {0xc0001351d0, 0x1, 0x5?})
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/cmd/internal/base/base.go:190 +0x2af
github.com/spf13/cobra.(*Command).execute(0xc0001f5500, {0xc000135180, 0x5, 0x5})
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f4c00)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/user/go/pkg/mod/entgo.io/ent@v0.12.3/cmd/ent/ent.go:24 +0xc5
exit status 2
make[1]: *** [Makefile:89: db] Error 1
make[1]: Leaving directory '/home/user/Projects/ordinals/OrdinalsIndexer'
make: *** [Makefile:97: all] Error 2
```

Thanks in advance :)

**Comment by adshao** [comment]
Should be fixed now.
